//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func validate() throws {

  }


  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 65 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: Add new task
      ///
      /// Key: schedule_notes_accessibility_add_task
      ///
      /// Locales: en, ja, zh
      func schedule_notes_accessibility_add_task() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_accessibility_add_task", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Task: %@
      ///
      /// Key: schedule_notes_accessibility_task_row
      ///
      /// Locales: en, ja, zh
      var schedule_notes_accessibility_task_row: RswiftResources.StringResource1<String> { .init(key: "schedule_notes_accessibility_task_row", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// en translation: Add
      ///
      /// Key: schedule_notes_add_button_title
      ///
      /// Locales: en, ja, zh
      func schedule_notes_add_button_title() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_add_button_title", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Schedule Notes
      ///
      /// Key: schedule_notes_app_name
      ///
      /// Locales: en, ja, zh
      func schedule_notes_app_name() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_app_name", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Cancel
      ///
      /// Key: schedule_notes_button_cancel
      ///
      /// Locales: en, ja, zh
      func schedule_notes_button_cancel() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_button_cancel", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Delete
      ///
      /// Key: schedule_notes_button_delete
      ///
      /// Locales: en, ja, zh
      func schedule_notes_button_delete() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_button_delete", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: This can’t be undone.
      ///
      /// Key: schedule_notes_confirm_delete_message
      ///
      /// Locales: en, ja, zh
      func schedule_notes_confirm_delete_message() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_confirm_delete_message", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Delete task?
      ///
      /// Key: schedule_notes_confirm_delete_title
      ///
      /// Locales: en, ja, zh
      func schedule_notes_confirm_delete_title() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_confirm_delete_title", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Edit task
      ///
      /// Key: schedule_notes_edit_task_placeholder
      ///
      /// Locales: en, ja, zh
      func schedule_notes_edit_task_placeholder() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_edit_task_placeholder", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Tap below to add one
      ///
      /// Key: schedule_notes_empty_list_subtitle
      ///
      /// Locales: en, ja, zh
      func schedule_notes_empty_list_subtitle() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_empty_list_subtitle", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: No tasks yet
      ///
      /// Key: schedule_notes_empty_list_title
      ///
      /// Locales: en, ja, zh
      func schedule_notes_empty_list_title() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_empty_list_title", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Network error. Check your connection.
      ///
      /// Key: schedule_notes_error_network
      ///
      /// Locales: en, ja, zh
      func schedule_notes_error_network() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_error_network", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Couldn’t save. Try again.
      ///
      /// Key: schedule_notes_error_save_failed
      ///
      /// Locales: en, ja, zh
      func schedule_notes_error_save_failed() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_error_save_failed", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: All
      ///
      /// Key: schedule_notes_filter_all
      ///
      /// Locales: en, ja, zh
      func schedule_notes_filter_all() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_filter_all", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Completed
      ///
      /// Key: schedule_notes_filter_done
      ///
      /// Locales: en, ja, zh
      func schedule_notes_filter_done() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_filter_done", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Pending
      ///
      /// Key: schedule_notes_filter_pending
      ///
      /// Locales: en, ja, zh
      func schedule_notes_filter_pending() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_filter_pending", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Notes List
      ///
      /// Key: schedule_notes_list_title
      ///
      /// Locales: en, ja, zh
      func schedule_notes_list_title() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_list_title", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Modify
      ///
      /// Key: schedule_notes_modify_button_title
      ///
      /// Locales: en, ja, zh
      func schedule_notes_modify_button_title() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_modify_button_title", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Enter new task
      ///
      /// Key: schedule_notes_new_task_placeholder
      ///
      /// Locales: en, ja, zh
      func schedule_notes_new_task_placeholder() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_new_task_placeholder", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Next
      ///
      /// Key: schedule_notes_onboarding_next
      ///
      /// Locales: en, ja, zh
      func schedule_notes_onboarding_next() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_onboarding_next", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Skip
      ///
      /// Key: schedule_notes_onboarding_skip
      ///
      /// Locales: en, ja, zh
      func schedule_notes_onboarding_skip() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_onboarding_skip", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Capture what you need to do
      ///
      /// Key: schedule_notes_onboarding_subtitle
      ///
      /// Locales: en, ja, zh
      func schedule_notes_onboarding_subtitle() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_onboarding_subtitle", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Welcome
      ///
      /// Key: schedule_notes_onboarding_title
      ///
      /// Locales: en, ja, zh
      func schedule_notes_onboarding_title() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_onboarding_title", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: %lld tasks
      ///
      /// Key: schedule_notes_plural_task_count
      ///
      /// Locales: en, ja, zh
      var schedule_notes_plural_task_count: RswiftResources.StringResource1<Int> { .init(key: "schedule_notes_plural_task_count", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// en translation: Save
      ///
      /// Key: schedule_notes_save_button_title
      ///
      /// Locales: en, ja, zh
      func schedule_notes_save_button_title() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_save_button_title", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Search tasks…
      ///
      /// Key: schedule_notes_search_placeholder
      ///
      /// Locales: en, ja, zh
      func schedule_notes_search_placeholder() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_search_placeholder", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Buy milk
      ///
      /// Key: schedule_notes_seed_task_buy_milk_title
      ///
      /// Locales: en, ja, zh
      func schedule_notes_seed_task_buy_milk_title() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_seed_task_buy_milk_title", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Organize meeting minutes
      ///
      /// Key: schedule_notes_seed_task_meeting_minutes_title
      ///
      /// Locales: en, ja, zh
      func schedule_notes_seed_task_meeting_minutes_title() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_seed_task_meeting_minutes_title", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Copied to clipboard
      ///
      /// Key: schedule_notes_snackbar_copied
      ///
      /// Locales: en, ja, zh
      func schedule_notes_snackbar_copied() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_snackbar_copied", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Inbox
      ///
      /// Key: schedule_notes_tab_inbox
      ///
      /// Locales: en, ja, zh
      func schedule_notes_tab_inbox() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_tab_inbox", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Settings
      ///
      /// Key: schedule_notes_tab_settings
      ///
      /// Locales: en, ja, zh
      func schedule_notes_tab_settings() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_tab_settings", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Today
      ///
      /// Key: schedule_notes_tab_today
      ///
      /// Locales: en, ja, zh
      func schedule_notes_tab_today() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_tab_today", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Due today
      ///
      /// Key: schedule_notes_task_due_today
      ///
      /// Locales: en, ja, zh
      func schedule_notes_task_due_today() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_task_due_today", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Due tomorrow
      ///
      /// Key: schedule_notes_task_due_tomorrow
      ///
      /// Locales: en, ja, zh
      func schedule_notes_task_due_tomorrow() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_task_due_tomorrow", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Overdue
      ///
      /// Key: schedule_notes_task_overdue
      ///
      /// Locales: en, ja, zh
      func schedule_notes_task_overdue() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_task_overdue", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Reminder: %@
      ///
      /// Key: schedule_notes_test_accessibility_reminder
      ///
      /// Locales: en, ja, zh
      var schedule_notes_test_accessibility_reminder: RswiftResources.StringResource1<String> { .init(key: "schedule_notes_test_accessibility_reminder", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// en translation: Task: %@
      ///
      /// Key: schedule_notes_test_accessibility_task_row
      ///
      /// Locales: en, ja, zh
      var schedule_notes_test_accessibility_task_row: RswiftResources.StringResource1<String> { .init(key: "schedule_notes_test_accessibility_task_row", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// en translation: Export
      ///
      /// Key: schedule_notes_test_action_export
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_action_export() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_action_export", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Import
      ///
      /// Key: schedule_notes_test_action_import
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_action_import() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_action_import", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Cancel
      ///
      /// Key: schedule_notes_test_cancel
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_cancel() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_cancel", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Close
      ///
      /// Key: schedule_notes_test_confirm_close
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_confirm_close() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_confirm_close", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: OK
      ///
      /// Key: schedule_notes_test_confirm_ok
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_confirm_ok() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_confirm_ok", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Add your first task.
      ///
      /// Key: schedule_notes_test_empty_state_subtitle
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_empty_state_subtitle() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_empty_state_subtitle", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: No tasks yet
      ///
      /// Key: schedule_notes_test_empty_state_title
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_empty_state_title() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_empty_state_title", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Please try again later.
      ///
      /// Key: schedule_notes_test_error_generic_message
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_error_generic_message() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_error_generic_message", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Something went wrong
      ///
      /// Key: schedule_notes_test_error_generic_title
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_error_generic_title() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_error_generic_title", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Network unavailable
      ///
      /// Key: schedule_notes_test_error_network
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_error_network() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_error_network", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Request timed out
      ///
      /// Key: schedule_notes_test_error_timeout
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_error_timeout() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_error_timeout", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Loading…
      ///
      /// Key: schedule_notes_test_loading
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_loading() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_loading", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: New task
      ///
      /// Key: schedule_notes_test_new_task_button
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_new_task_button() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_new_task_button", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: %lld days
      ///
      /// Key: schedule_notes_test_plural_day_count
      ///
      /// Locales: en, ja, zh
      var schedule_notes_test_plural_day_count: RswiftResources.StringResource1<Int> { .init(key: "schedule_notes_test_plural_day_count", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// en translation: Off
      ///
      /// Key: schedule_notes_test_reminder_off
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_reminder_off() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_reminder_off", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: On
      ///
      /// Key: schedule_notes_test_reminder_on
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_reminder_on() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_reminder_on", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Daily
      ///
      /// Key: schedule_notes_test_repeat_daily
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_repeat_daily() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_repeat_daily", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Monthly
      ///
      /// Key: schedule_notes_test_repeat_monthly
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_repeat_monthly() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_repeat_monthly", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Does not repeat
      ///
      /// Key: schedule_notes_test_repeat_none
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_repeat_none() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_repeat_none", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Weekly
      ///
      /// Key: schedule_notes_test_repeat_weekly
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_repeat_weekly() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_repeat_weekly", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Retry
      ///
      /// Key: schedule_notes_test_retry
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_retry() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_retry", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Copied
      ///
      /// Key: schedule_notes_test_snackbar_copied
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_snackbar_copied() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_snackbar_copied", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Deleted
      ///
      /// Key: schedule_notes_test_snackbar_deleted
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_snackbar_deleted() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_snackbar_deleted", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Saved
      ///
      /// Key: schedule_notes_test_snackbar_saved
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_snackbar_saved() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_snackbar_saved", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Location
      ///
      /// Key: schedule_notes_test_task_location_label
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_task_location_label() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_task_location_label", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Time
      ///
      /// Key: schedule_notes_test_task_time_label
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_task_time_label() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_task_time_label", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Task title
      ///
      /// Key: schedule_notes_test_task_title_label
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_task_title_label() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_task_title_label", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

      /// en translation: Task reminder
      ///
      /// Key: schedule_notes_test_toggle_reminder
      ///
      /// Locales: en, ja, zh
      func schedule_notes_test_toggle_reminder() -> String {
        let resource: RswiftResources.StringResource = .init(key: "schedule_notes_test_toggle_reminder", tableName: "Localizable", source: source, developmentValue: nil, comment: nil)
        return resource()
      }

    }
  }
}